### ISSUE TITLE
strange focus behaviour

### ISSUE THREAD

**Issue by slillo** [gund/ng-dynamic-component#103]
Please take a look at this [example](https://stackblitz.com/edit/angular-dyncomps)

AppComponent dinamically insert InputComponent, each InputComponent dinamically insert LabelComponent (before the input), SvuotaComponent (just a button immediately after the input field, that empty the input) and ErrorComponent (after the button).

Buttons are disabled until input fields are empty. While inputs are empty if you press tab focus works as expected, button are skipped and focus jump to the next input.

If you fill an input field and the focus is on the input filled, you need to press tab two times in order to focus on button, and, even stranger, you need to click two times on button for the click event to be managed.

If I 'statically' put a button after input tab and click work as expected.

**Comment by gund** [comment]
Hi, thanks for creating example.

I tried it on the phone with voice over and saw that focus jumped to the page which is odd.

My only guess for now is that there is something to do with change detection, and when you move focus for a brief moment in time html loses all dynamic components at which point browser sets focus somewhere else and by the time they are rendered back focus is already set.

What you can do is try to use everywhere `ChangeDetectionStrategy.OnPush` and make sure you do not use getters as properties that return something more complex that primitive values, since change detection will think the value has changed and will perform unnecessary rerenders.

Unfortunately I'm right now cannot access any computer to try and test it more in depth.

**Comment by gund** [comment]
Hey, I did some testing and found that your button components every time are recreated when interaction happens (either by focus changes on the page or by typing somewhere), you can see that here: https://stackblitz.com/edit/angular-dyncomps-x29gq4

Basically number near each component in parenthesis indicates current id of component and if it changes it means that is was recreated.

The reason you are getting this updates is because you are using computed properties for inputs such as `get prec()` or `get succ()` which means every time Angular gets their values they are effectively new objects/arrays and angular will rerun change detection for them as the value have changed.

My advice here is basically compute those values once and store in property.

**Comment by gund** [comment]
I've worked on your example app to demonstrate the approach you can take to fix those extra changes: https://stackblitz.com/edit/angular-dyncomps-fixed

Basically I'm caching all the dynamic components data so that it won't trigger any extra changes, but then your inputs have to be updated when needed, so I created extra private method called `_updateValue()` that is triggered every time value changes and it loops through cached computed addons and updates the value input for each.

That technique completely reduces extra change detection cycles and fixes the issue with focus once and for all.

Please let me know if you have any questions or want some more explanations, but for now I will close the issue as the library does it's job as advertised =)

**Comment by gund** [comment]
I also added modified version where you might have some async update which does not come from UI (like backend) in which case you will have to manually tell Angular to rerender particular template via `ChangeDetectorRef`.

Check it out here: https://stackblitz.com/edit/angular-dyncomps-fixed-with-update
(the label of every component is updated after 2 secs).

You can note that I added calls to `ChangeDetectorRef#markForCheck()` in methods like `_updateLabel()` to let Angular propagate changes immediately to sub-components.
