### ISSUE TITLE
Pass attributes to dynamic component

### ISSUE THREAD

**Issue by nickbullock** [gund/ng-dynamic-component#120]
Hi! Thank you for this library.
How can i pass attributes(class for example)  to dynamic components?
```
<ndc-dynamic [ndcDynamicComponent]="component"
                 [ndcDynamicInputs]="inputs"
                 [ndcDynamicOutputs]="outputs"
                 [classForDynamicComponent]="???"
    >
    </ndc-dynamic>
```

**Comment by gund** [comment]
Well unfortunately right now you have to do it yourself imperatively (not via html).

And the way you can set attributes is by using `<ndc-dynamic>` component to inject dynamic component and then grabbing it's reference in your host component via `@ViewChild` and then using it's `componentRef` public property which in turn will have `location` property of type `ElementRef`.

That that can be used along with `Renderer2` to set classes etc.

So here's example:
```ts
import { DynamicComponent } from 'ng-dynamic-component';

@Component({
  selector: 'my-component',
  template: `
    <ndc-dynamic [ndcDynamicComponent]="dynamicComp"></ndc-dynamic>
`
})
export class MyComponent implements AfterViewInit {
  dynamicComp = SomeComponent;
  @ViewChild(DynamicComponent) ndcDynamic: DynamicComponent;

  constructor(private renderer: Renderer2) {}

  ngAfterViewInit() {
    const dynamicElementRef = this.ndcDynamic.componentRef.location;
    this.renderer.setClass(dynamicElementRef.nativeElement, 'my-class');
  }
}
```

_NOTE_: You have to set your dynamic class only `AfterViewInit` because that's when angular will provide you requested `ViewChild` (it will not be set in `OnInit` hook).

**Comment by gund** [comment]
Btw for the time being you can create a more usable solution for yourself.

You can extend `DynamicComponent` with new component that will additionally accept a set of attributes and internally assign them using the method I described above.

And then when you import `DynamicModule` just pass new component as a second argument to `withComponents()` method so that it will be used instead of default `<ndc-dynamic>`.

**Comment by nickbullock** [comment]
Thank you sir!

**Comment by gund** [comment]
Hey @nickbullock, if you want you can try a new directive added in new release that will allow to set attributes right from your templates.

Let me know how it works for you =)
