### ISSUE TITLE
Add directive to dynamic component?

### ISSUE THREAD

**Issue by RealFighter64** [gund/ng-dynamic-component#160]
First of all, thanks so much for the library. It's really helped me to get my application up and running.
However, I was just wondering if it is possible to add a directive to a component generated by NDC. I'm trying to use a directive to get the dynamic components as a set of ViewChildren, but I'm having trouble applying the directive to every instance of the dynamic component.
For example:
```
<ndc-dynamic
            *ngFor="let componet of components"
            [ndcDynamicComponent]="component"
            [ndcDynamicInputs]="{ ... }"
            [ndcDynamicDirectives]="myDirective">
</ndc-dynamic>
```

**Comment by gund** [comment]
Hi, right now it is not possible to apply directives to dynamic component since this process is only available via templating (because angular compiles all templates).

So your workaround can be to create a wrapper component that applies required directives to your component and then you render that wrapper dynamically. Not ideal but will work right now.

There is a chance that applying directives manually might be feasible.
I might explore that area later, it all depends if `ViewContainerRef` or `ComponentRef` can provide `component` specific injector so we can manually instantiate needed directives and resolve all tokens.

Also even if that will be possible there might be a limitation that `@Hostbinding` and `@HostListener` will not work and that might be even harder to implement manually.

**Comment by RealFighter64** [comment]
Thanks for the fast reply! I'll see what I can do.

**Comment by alexandremoore** [comment]
@RealFighter64 were you able to work around this? I tried to wrap my component like @gund  suggested but it didn't work.

**Comment by gund** [comment]
I started investigation on this topic here: https://github.com/gund/test-dynamic-directives
