### ISSUE TITLE
How to use ng-dynamic-component across multiple lazy loaded (visited) modules (pages)?

### ISSUE THREAD

**Issue by DeepakArora76** [gund/ng-dynamic-component#236]
What I have in my mind is to use available directives from `ng-dynamic-component` in the root module without registering `(without importing DynamicModule.withComponents) `dynamic components (which are available in some other lazy loaded modules). 

Appreciate an example on this.

**Comment by gund** [comment]
You can always pass empty array to `DynamicModule.withComponents([])` in your root module.

And then in your lazy modules just import `DynamicModule` to get directives/components.

Will that work for you?

**Comment by roseyda** [comment]
Hi,
My question may be stupid, but I don't understant how it is possible to lazy load component with ng-dynamic-component.
Is lazy loading possible with this library ?
If yes, how ?

Thanks in advance for your feedback

**Comment by DeepakArora76** [comment]
I have come up with my own solution. Below is snippet for your reference. I will not be getting into the details of it. 

```JavaScript
  async getDynamicComponentUsingCompileAndLoad(componentName: string): Promise<ComponentRef<any>> {
    let moduleFactory = this.getModuleFactoryByModuleId(componentName);
    if (moduleFactory == null) {
      moduleFactory = await this.getModuleFactoryByLoadingModule(componentName);
    }

    if (moduleFactory == null) {
      return this.getDynamicContentErrorComponent(
        `Unable to load module for the component ${componentName}.`
      );
    }

    try {
      const moduleReference = moduleFactory.create(this.injector);
      const moduleFactories = await this.compiler.compileModuleAndAllComponentsAsync(moduleFactory.moduleType);
      const componentFactory = moduleFactories.componentFactories
        .find(e => e.componentType.name === componentName);
      const compReference = componentFactory.create(moduleReference.injector, null, null, moduleReference);
      moduleReference.destroy();
      return compReference;
    } catch (error) {
      console.error((<Error>error).message);
      return this.getDynamicContentErrorComponent(
        `Unable to load module for the component ${componentName}.`
      );
    }
  }
```

**Comment by gund** [comment]
@DeepakArora76 thanks for sharing your solution. However I should point a important thing:
you do not need to recompile existing module factory to get it's component factories since it already was compiled. You can directly access factories when module is created via `moduleRed.componentFactoryResolver` (see https://angular.io/api/core/NgModuleRef)

Regarding example for @roseyda I think the simplest one is by only importing your component in the module where you need to use it and then lazyload that module via router's `loadChildren`.

So:
1. Import dynamic component to module you will use:
```ts
@NmModule({
  imports: [DynamicModule.withComponents([MyComponent])],
  declarations: [MyComponent]
})
export class MyModule {}
```
2. Then lazyload the whole module from route:
```ts
@NgModule({
  imports: [RouterModule.forRoot([
    {path: 'my', loadChildren: './path/to/my.module#MyModule'}
  ])]
})
export class AppModule {}
```

This will automatically put dynamic component and it's module into separate chunk and angular will then take care of loading that chunk on demand.

If you cannot use router for lazy-loading then you have to manually take care of loading proper chunk in runtime and that is beyond the scope of this package.

As an example you can have a look at https://www.npmjs.com/package/@herodevs/lazy-af library - it lazyloads any component that you set to separate chunk. But you will then have to be able to extract loaded module from it and that is up to that library how to do it.

**Comment by roseyda** [comment]
Hi @DeepakArora76  and @gund 
Thanks a lot for your feedback

**Comment by gund** [comment]
Closing as this seems to be resolved.
