### ISSUE TITLE
ie11

### ISSUE THREAD

**Issue by Sebush** [gund/ng-dynamic-component#245]
Hi, 

we need ie11-compatibility.
is it possible to deploy a well transpiled package to npm-repo?

**Comment by gund** [comment]
As far as I can tell es5 bundle should be good to go in IE11...

Did you try to use it in your app with IE11? If so what kind of error did you get?

**Comment by roseyda** [comment]
+1 I'ma facing the same issue.
Actually, I'm using reactive-component-loader library (https://github.com/wishtack/wishtack-steroids) which depends on ng-dynamic-component.
But even when building my app with es5 in my tsconfig.json, I get ng-dynamic-component es2015 code included in my vendor.js
Thus IE11 complains because it don't kwon "class" keyword.

**Comment by yjaaidi** [comment]
I guess this is related to this issue https://github.com/gund/ng-dynamic-component/issues/225.
I might get rid of `wtLazy` structural directive in `@wishtack/reactive-component-loader` (but still keep the `wt-lazy` component of course) to fix the issue.

**Comment by taivu** [comment]
> As far as I can tell es5 bundle should be good to go in IE11...

can you show example code to import the library's es5 bundle?

**Comment by gund** [comment]
This is what happens by default when you build using angular CLI.

Otherwise you have to manually specify which field to resolve inside your webpack config from the package.json files.

You can check out how to configure this here: https://webpack.js.org/configuration/resolve/#resolvemainfields

This lib will have ES5 build inside `module` field, so it should be the first in the list (ref: https://github.com/gund/ng-dynamic-component/blob/master/package.json#L7)

**Comment by roseyda** [comment]
Hi all,
On my case, the is was comming from reactive-component-loader library.
And now my issue is fixed

**Comment by taivu** [comment]
ohhh. got it. thank you for the explanation!

**Comment by gund** [comment]
Closing as this seems to be resolved.
