### ISSUE TITLE
ngOnChanges produces changes for every input, even when the objects are unchanged.

### ISSUE THREAD

**Issue by Jrubzjeknf** [gund/ng-dynamic-component#403]
Problem: `ngOnChanges` seems to always provide all inputs in the SimpleChanges object, even though some inputs are unchanged. Correct behavior would be that only the changed inputs are provided, similar to the Angular implementation.

Repro steps:
- Open [stackblitz](https://stackblitz.com/edit/angular-ivy-bdrnl1?file=src/app/app.component.html)
- Click on `val1` button, which changes the `someValue` property on `HelloComponent`.
- Notice in the console that the following SimpleChanges object is generated. The issue is that `name` should not come up as a change, since it has not changed.
```js
{
  "name": {
    "previousValue": "World",
    "currentValue": "World",
    "firstChange": false
  },
  "someValue": {
    "previousValue": "myvalue",
    "currentValue": "val1",
    "firstChange": false
  }
}
```

My own debugging shows that all bound input properties are always marked as changed. I can work around it for now by checking for equality myself in the `ngOnChanges` method of my component, but a fix would of course be preferable.

**Comment by gund** [comment]
Thanks for reporting this issue!
It does look like it's creating changes for unchanged inputs which is super weird as it did not do it before...

I will investigate what is the cause and fix it soon.

**Comment by gund** [comment]
Okay so after my investigation I figured out that this is a regression in Angular's `KeyValueDiffer` Service that this library uses in order to figure out the changes in inputs - it basically reports all properties to be changed even if just one property in object was changed...

I'm not sure if this was a change by design or a regression in Angular so I'm going to open an issue there and ask for clarification.

After their response we will know how to address this bug but for now I would recommend you to simply do a reference checks in `OnChanges` hook manually.

**Comment by gund** [comment]
During deeper investigation is turns out that Angular's differ works fine and library was using incorrect API to collect changes from it.

Currently new records are collected from `forEachAddedItem()` method and changed records from `forEachItem()` method which always returns all items despite any changes (which is logical).
See: https://github.com/gund/ng-dynamic-component/blob/a4dd16067907df6b975b757369ae482b2bbc32c3/projects/ng-dynamic-component/src/lib/io/io.service.ts#L241-L245

But there is another method `forEachChangedItem()` that returns only changed records and behaves correctly.
See demo https://stackblitz.com/edit/angular-keyvalue-differ?file=src%2Fapp%2Fapp.component.ts

So I'm preparing a fix now and will release soon.
Thanks again for the reported bug with reproduction demo!

**Comment by Jrubzjeknf** [comment]
Thanks for your quick investigation and solution! Awesome to see that this package is so well supported. 😊

Will the change also be pushed to the `@no-barrels` tag? Apparently I need the package from that tag to build with Ivy.
