### ISSUE TITLE
DynamicModule.withComponents

### ISSUE THREAD

**Issue by b348** [gund/ng-dynamic-component#425]
Hey, 

I used the following lines:
```
@NgModule({
  imports: [BrowserModule, FormsModule, DynamicModule.withComponents([TestAComponent, TestBComponent])],
  declarations: [AppComponent, TestAComponent, TestBComponent],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

Each of these Modules have a custom @ typescript decorator:

```
@Component({
  selector: 'testA',
  templateUrl: './testA.component.html',
  styleUrls: ['./testA.component.css']
})
@MyCustomDecorator("TestAComponent")
export class TestAComponent implements OnInit {
...
```

This custom decorator will be executed automatically because of "withComponents" (without withComponents it wont be executed in some way by withComponents). The decorator add some data to an array in a custom service (that is exported public) to "register" all my dynamic components. But now withComponents got removed. Now my array is empty and I cannot register my components via a decorator. A way to fix that is of course is to for example run in the constructor of the service a custom function named "loadComponents" and run the decorator-function (that noramlly should run by using the decorator). But now I'm asking if its the only way? I thought I can do that easly by adding this decorator. Is there now a better way? Thanks

**Comment by gund** [comment]
Hi, so the static method `withComponents()` was removed to not force every dynamic component to be loaded even when they are not used/needed and to allow lazy loading to be controlled by the developer instead of the library.

Now the decorators will be always executed as long as the code of component is loaded withing the bundle.

If they are not executed it simply means that you haven't loaded them into your bundle (either main or some lazy chunk).

And this probably happened because you removed those imports from the AppModule.

So it's really up to you to decide how and where to import/load those components.

You can import them somewhere in the service or in module.

I would advise to avoid relying on decorators to load components as you see it's not reliable and you still need to have an import of comment somewhere in the app.

And since you need the import anyway you can replace decorator with some kind of service where you register all component in static property or even DI token (like InjectionToken) and then process those components the same way you do in decorator.

**Comment by b348** [comment]
Okay all right, got it, thank you very much!
