### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by muhamedkarajic** [gund/ng-dynamic-component#486]
Today we have been using the new version 10.5.0 and it seems like it requies angular cli 14 and above. Which kind of dosent make sence due to the fact that that was only a minor update.

Please if possible revert those changes cause in my company we use a lot of libraries (our own) which internally depend on that one.

**Comment by gund** [comment]
Hey, yes a just from Angular 13 to 14 was done in a minor update because initially we planned to support both versions in the same major but it turned out that the Angular compiler does not support forward compatibility even between minors (which I [opened an issue about](https://github.com/angular/angular/issues/46398) to clarify and they are explicitly do not guarantee this).

Unfortunately reverting is no longer an option as there are 2 more minor versions being published for quite a long time now.
So you will need to pin down the version to minor lock (using tilda `~` instead of a caret `^`) which should solve the problem for all your projects.
