### ISSUE TITLE
Unknown input error after updating from no-barrels version [Bug] 

### ISSUE THREAD

**Issue by mawro453** [gund/ng-dynamic-component#506]
**Describe the bug**
We are currently using version 10.1.1-no-barrels.1 of the library, and we encountered multiple error logs in the console after updating to either version 10.5.1 or 10.7.0. One of the error logs is as follows:
```
NG0303: Can't set value of the 'rowsSelectable' input on the 'HierarchicalTableComponent' component. Make sure that the 'rowsSelectable' property is annotated with @Input() or a mapped @Input('rowsSelectable') exists.
```

However, we have noticed that the component still works as expected despite the error logs.

**Expected behavior**
We would expect that the newest library version would not produce any error logs when using the component. If this is not possible, we would appreciate a no-barrels version for version 10.7.0 to be made available.

**Environment:**
 - OS: Windows 10 Pro
 - Browser: Chrome Version 111.0.5563.147
 - Library version: 10.7.0
 - Angular version: 14.2.5

**Comment by gund** [comment]
The error has nothing to do with `no-barrels` NPM tag and the error comes directly from Angular v14 which now validates that your dynamic component actually declares the input that you are trying to set on it.
So you should follow the advice from the error message and annotate your inputs with `@Input` decorators on dynamic components to get rid from the error.

The `no-barrels` NPM tag is no longer maintained and discontinued from support/updates as the upstream bug that was fixed by it is already fixed and thus is no longer needed.
