### ISSUE TITLE
[Bug] Angular 16 compatibility 

### ISSUE THREAD

**Issue by AmrAbdulrahman** [gund/ng-dynamic-component#516]
**Describe the bug**
Not really a bug, but how can we make sure the library is compatible with angular 16? I can see used version is 14.

**Comment by gund** [comment]
There were already the same questions such as #512 and #513.

Long story short - I'm keeping forward compatibility with angular v14 for as long as possible until angular themselves will break it in any future new versions. So far it's perfectly compatible with every angular version since v14 onward.
Since this library does not package any angular dependency, there is absolutely no issue with it being compiled by angular v14 compiler as long as future angular compilers can consume it.

**Comment by hosamaly** [comment]
Since this issue keeps coming up, may I suggest adding something to the README to say which versions of Angular it's been tested against?

It would be great if these versions could be added to the CI matrix as well.

**Comment by gund** [comment]
@hosamaly readme does state compatibility with version v14 onwards in the compatibility table.
Until angular introduces breaking changes this will hold true for all future versions.
For now I'm not planning on adding BC matrix tests to CI myself, any issues that arise in any new versions can be reported here and will be addressed asap, so the CI won't really add much value as we already know that lib works with all currently released versions anyway.
With that said I can accept a PR that adds such a matrix tests to github CI workflow.
