### ISSUE TITLE
how to add @Input/@Output Decorators dynamically to component properties?

### ISSUE THREAD

**Issue by checo06** [gund/ng-dynamic-component#84]
Hi! Everybody likes this tool so im trying to use it :)

My doubt is due to this post ( https://stackoverflow.com/a/39507831/1546652 ) i could notice how to add properties dynamically to an existing component ( via Object.assign() ) but i cant figure out how to add @Input/@Output Decorators dynamically to a property. I suppose this is done via Object api.

**Comment by gund** [comment]
Hi!

You are right that inputs are updated via simple property assignment, and outputs via simple subscription and then for every inputs change it generates appropriate life-cycle hooks so for your component it looks like your inputs were decorated with `@Input`.

That leads you to a conclusion that your component do not have to have at all any `@Input/@Output` decorators but you have to be careful with outputs though because of one of them will not exist at runtime the library will fail to subscribe an an error will be thrown.

**Comment by checo06** [comment]
Thanks a lot for your fast answer Alex!

Well i think your answer totally clears the situation. Just to close this, do you think is possible in javascript to add decorators dynamically to properties of an object? (for example using the Object api)

**Comment by gund** [comment]
If we are talking about property decorators on class I think it's not possible, because decorators have to be defined on static property before any instance will be constructed but JavaScript does not allow you to know which properties it will have before you do instantiation.

So in purr javascript I guess no, but in Typescript probably you can, but you will have to do that via code-generation (you can come up with one generic decorator being applied on class that can take another decorator as argument and than codegen will apply that decorator on each property).

But you know this is quite tricky so I guess the effort does not worth it =)

Just curious, why do you want to add decorators dynamically anyway?

**Comment by checo06** [comment]
Mmm.. seems complicated the dynamic injection of annotations.

I only wanted to know the dynamic injection of decorators on dynamic properties just as a cultural thing.. i only was thinking to use it to decorate the properties in the way i explained on my first post but with your advice my doubts are cleared and  the universe once again is a fair place to live.. :) 

thanks a lot dude!

**Comment by gund** [comment]
No problem =)
