### ISSUE TITLE
AppModule Providers not working inside ndc-dynamic

### ISSUE THREAD

**Issue by xbotuk** [gund/ng-dynamic-component#97]
I have been trying to pass on the common instances of the AppModule Providers inside ndc-dynamic but unsuccessful so far. Here are the things I have tried

(1) without [ndcDynamicProviders], it seems the components are getting 'undefined' object instances of the services

(2) with [ndcDynamicProviders], it seems new object instances of the services getting created, which are different to the object instances available via components constructors under AppModule.

What I require is the exact object instances that are available inside AppModule.

Some help would be really appreciated.

**Comment by gund** [comment]
By default you should be able to get everything what is available in your root injector because that is what used as the parent injector for the dynamically created components.

So you should be able to access your stuff from AppModule without any extra providers required.

Would you please create a plunkr with the issue you are having?

**Comment by xbotuk** [comment]
I have resolved this by using ViewContainerRef.parentInjector
